package se.natusoft.tools.optionsmgr.internal.utils;

import org.w3c.dom.Attr;
import se.natusoft.tools.codelicmgr.annotations.*;
import se.natusoft.tools.codelicmgr.enums.Source;

/**
 * This is an attribute of an XMLElement DOM Element wrapper.
 */
@Project(
    name="OptionsManager",
    description="Manages application/tool options. Options are mapped to Java Bean properties" +
                "using annotations. Help texts can be specified for options also using" +
                "annotations and a complete help text can be generated by the options manager." +
                "Options can be loaded from command line arg String[] array, an XML file, or a" +
                "java properties file."
)
@Copyright(year="2009", holder="Natusoft AB", rights="All rights reserved.")
@License(
    type="Apache",
    version="2.0",
    description="Apache Software License",
    source=Source.OPEN,
    text={
        "Licensed under the Apache License, Version 2.0 (the 'License');",
        "you may not use this file except in compliance with the License.",
        "You may obtain a copy of the License at",
        "",
        "  http://www.apache.org/licenses/LICENSE-2.0",
        "",
        "Unless required by applicable law or agreed to in writing, software",
        "distributed under the License is distributed on an 'AS IS' BASIS,",
        "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        "See the License for the specific language governing permissions and",
        "limitations under the License."
    }
)
@Authors({
    @Author(
        name="Tommy Svensson",
        email="tommy@natusoft.se",
        changes={
            @Change(when="2009-12-15", description="Created")
        }
    )
})
public class XMLAttribute extends Object {
    //
    // Private class members
    //
    
    /** The name of the attribute. */
    private String name = null;
    
    /** The value of the attribute */
    private String value = null;
    
    //
    // Constructors
    //
    
    /**
     * Creates new XMLAttribute.
     *
     * @param name The name of the attribute.
     */
    public XMLAttribute(String name) {
        this.name = name;
    }
    
    /**
     * Creates new XMLAttribute.
     *
     * @param name The name of the attribute.
     * @param value The value of the attribute.
     */
    public XMLAttribute(String name, String value) {
        this.name = name;
        this.value = value;
    }
        
    /**
     * Creates a new XMLAttribute.
     *
     * @praam attribute A DOM Attr object.
     */
    /*package*/ XMLAttribute(Attr attribute) {
        this.name = attribute.getName();
        this.value = attribute.getValue();
        if (this.value != null && this.value.trim().length() == 0) {
            this.value = null;
        }        
    }
    
    //
    // Methods
    //

    /**
     * Gets the name of the attribute.
     */
    public String getName() {
        return this.name;
    }
    
    /**
     * Sets the value of the attribute.
     *
     * @param value The value to set.
     */
    public void setValue(String value) {
        this.value = value;
    }
    
    /**
     * Gets the value of the attribute.
     */
    public String getValue() {
        return this.value;
    }
        
}
