package se.natusoft.tools.optionsmgr;

import java.io.InputStream;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import static org.junit.Assert.*;
import se.natusoft.tools.codelicmgr.annotations.*;
import se.natusoft.tools.codelicmgr.enums.Source;

/**
 * Tests XMLAttributeOptionsManager functionality.
 */
@Project(
    name="OptionsManager",
    codeVersion="1.0",
    description="Manages options. Options are mapped to Java Bean setters using annotations." +
                "Help texts can be specified for options also using annotations and a complete" +
                "help text can be generated by the options manager. Options can be loaded" +
                "from command line arg String[] array, an XML file, and a java properties file."
)
@Copyright(year="2009", holder="Natusoft AB")
@License(
    type="Apache",
    version="2.0",
    description="Apache License",
    source=Source.OPEN,
    text={
        "Licensed under the Apache License, Version 2.0 (the 'License');",
        "you may not use this file except in compliance with the License.",
        "You may obtain a copy of the License at",
        "",
        "  http://www.apache.org/licenses/LICENSE-2.0",
        "",
        "Unless required by applicable law or agreed to in writing, software",
        "distributed under the License is distributed on an 'AS IS' BASIS,",
        "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        "See the License for the specific language governing permissions and",
        "limitations under the License."
    }
)
@Authors({
    @Author(
        name="Tommy Svensson",
        email="tommy@natusoft.se",
        changes={
            @Change(when="2009-12-17", description="Created")
        }
    )
})
public class XMLAttributeOptionsManagerTest {

    public XMLAttributeOptionsManagerTest() {
    }

    @BeforeClass
    public static void setUpClass() throws Exception {
    }

    @AfterClass
    public static void tearDownClass() throws Exception {
    }

    @Before
    public void setUp() {
    }

    @After
    public void tearDown() {
    }

    /**
     * Test of loadOptions method, of class XMLAttributeOptionsManager.
     */
    @Test
    public void loadOptionsLessComplexOptionModel() throws Exception {

        InputStream xmlStream = getClass().getResourceAsStream("projectAttr.xml");
        
        XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex.Project> xaom =
                new XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex.Project>(se.natusoft.tools.optionsmgr.testmodels.complex.Project.class);

        se.natusoft.tools.optionsmgr.testmodels.complex.Project project = xaom.loadOptions(xmlStream);

        xaom.validateLoadedOptions("", "/");

//        System.out.println(project.toString());
        
        assertNotNull(project);
        assertTrue(project.getName().equals("testproj"));
        assertTrue(project.getDescription().equals("Some Description."));
        assertTrue(project.getProjectLicense().getLicenseType().equals("ASF"));
        assertTrue(project.getProjectLicense().getLicenseVersion() == 2);
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(0).getLicenseType().equals("GPL"));
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(0).getLicenseVersion() == 3);
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(1).getLicenseType().equals("LGPL"));
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(1).getLicenseVersion() == 2);
    }

    /**
     * Test of loadOptions method, of class XMLAttributeOptionsManager.
     */
    @Test
    public void loadOptionsMoreComplexOptionModel() throws Exception {

        InputStream xmlStream = getClass().getResourceAsStream("projectAttr2.xml");

        XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex2.Project> xaom =
                new XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex2.Project>(se.natusoft.tools.optionsmgr.testmodels.complex2.Project.class);

        se.natusoft.tools.optionsmgr.testmodels.complex2.Project project = xaom.loadOptions(xmlStream);

//        System.out.println(project.toString());

        assertNotNull(project);
        assertTrue(project.getName().equals("testproj"));
        assertTrue(project.getDescription().equals("Some Description."));
        assertTrue(project.getProjectLicense().getLicenseType().getValue().equals("ASF"));
        assertTrue(project.getProjectLicense().getLicenseVersion().getValue() == 2.0);
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(0).getLicenseType().getValue().equals("GPL"));
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(0).getLicenseVersion().getValue() == 3.0);
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(1).getLicenseType().getValue().equals("LGPL"));
        assertTrue(project.getThirdpartyLicenses().getLicenses().get(1).getLicenseVersion().getValue() == 2.0);
    }

    /**
     * Test of loadOptions method, of class XMLAttributeOptionsManager.
     */
    @Test
    public void loadOptionsValidateRequredValues() throws Exception {

        InputStream xmlStream = getClass().getResourceAsStream("projectAttrFaulty.xml");

        XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex.Project> xaom =
                new XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex.Project>(se.natusoft.tools.optionsmgr.testmodels.complex.Project.class);

        se.natusoft.tools.optionsmgr.testmodels.complex.Project project = xaom.loadOptions(xmlStream);

        assertNotNull(project);
        try {
            xaom.validateLoadedOptions("", "/");
            fail("This test is supposed to fail since it is missing the required 'project/name'!");
        }
        catch (OptionsException oe) {
            // OK this is expected!
        }

    }

    /**
     * Test of loadOptions method, of class XMLAttributeOptionsManager.
     */
    @Test
    public void loadOptionsHelpText() throws Exception {

        InputStream xmlStream = getClass().getResourceAsStream("projectAttr.xml");

        XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex.Project> xaom =
                new XMLAttributeOptionsManager<se.natusoft.tools.optionsmgr.testmodels.complex.Project>(se.natusoft.tools.optionsmgr.testmodels.complex.Project.class);

        se.natusoft.tools.optionsmgr.testmodels.complex.Project project = xaom.loadOptions(xmlStream);

        assertNotNull(project);

        String helpText = xaom.getHelpTextAsString("", "/");

        assertTrue(helpText.indexOf("Test of top level model general description.") >= 0);
        assertTrue(helpText.indexOf("project/name") > 0);
        assertTrue(helpText.indexOf("The project name.") > 0);
        assertTrue(helpText.indexOf("project/description") > 0);
        assertTrue(helpText.indexOf("A description of the project") > 0);
        assertTrue(helpText.indexOf("project/projectLicense/licenseType") > 0);
        assertTrue(helpText.indexOf("Specifies the license type.") > 0);
        assertTrue(helpText.indexOf("project/projectLicense/licenseVersion") > 0);
        assertTrue(helpText.indexOf("Specifies the license version.") > 0);
        assertTrue(helpText.indexOf("project/thirdparty/license/licenseType") > 0);
        assertTrue(helpText.indexOf("project/thirdparty/license/licenseVersion") > 0);

    }

}
