package se.natusoft.tools.optionsmgr.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import se.natusoft.tools.codelicmgr.annotations.*;
import se.natusoft.tools.codelicmgr.enums.Source;

/**
 * This annotation has 2 functions:
 * <ol>
 *   <li>Supply a generic description on the top level model that will be included in generated help text.</li>
 *   <li>Change the name of the model. This is most useful on the top level model which can have @OptionsModel(name="")
 *       to remove the top level model name from having to be specified in input option specifications. For example
 *       if you use the CommandLineOptionsManager and have an options model called Options you wouldn't want the
 *       user to have to specify options like "--options-path" or "--options-profile". Using this annotation and
 *       setting name to "" would give you "--path" and "--profile" instead. Never, ever set this to blank for any
 *       other than the top level model!! You can use this to change the name of any submodel but that can also
 *       be done in the parent with the "name" attribute of the @Option annotation on the submodel field which
 *       is probably a better way of doing it.</li>
 * </ol>
 */
@Project(
    name="OptionsManager",
    description="Manages application/tool options. Options are mapped to Java Bean properties" +
                "using annotations. Help texts can be specified for options also using" +
                "annotations and a complete help text can be generated by the options manager." +
                "Options can be loaded from command line arg String[] array, an XML file, or a" +
                "java properties file."
)
@Copyright(year="2009", holder="Natusoft AB", rights="All rights reserved.")
@License(
    type="Apache",
    version="2.0",
    description="Apache Software License",
    source=Source.OPEN,
    text={
        "Licensed under the Apache License, Version 2.0 (the 'License');",
        "you may not use this file except in compliance with the License.",
        "You may obtain a copy of the License at",
        "",
        "  http://www.apache.org/licenses/LICENSE-2.0",
        "",
        "Unless required by applicable law or agreed to in writing, software",
        "distributed under the License is distributed on an 'AS IS' BASIS,",
        "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        "See the License for the specific language governing permissions and",
        "limitations under the License."
    }
)
@Authors({
    @Author(
        name="Tommy Svensson",
        email="tommy@natusoft.se",
        changes={
            @Change(when="2009-11-26", description="Created")
        }
    )
})
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.TYPE, ElementType.METHOD})
public @interface OptionsModel {

    /**
     * Provides an optional name of the submodel. Default will be the field name. The Option annotation on the field can
     * also change the name.
     */
    String name() default "";

    /**
     * Provides a general description of all the options, and are only valid on the top level options model!
     * Anywhere else this will be ignored!
     */
    String description() default "";

}
