package se.natusoft.tools.optionsmgr.internal;

import se.natusoft.tools.optionsmgr.*;
import se.natusoft.tools.codelicmgr.annotations.*;
import se.natusoft.tools.codelicmgr.enums.Source;

/**
 * This is thrown when there are bugs found in OptionsManager code (when things are not as expected).
 * <p>
 * This exception should of course never be thrown!! It only exists as a help in debugging.
 */
@Project(
    name="OptionsManager",
    description="Manages application/tool options. Options are mapped to Java Bean properties" +
                "using annotations. Help texts can be specified for options also using" +
                "annotations and a complete help text can be generated by the options manager." +
                "Options can be loaded from command line arg String[] array, an XML file, or a" +
                "java properties file."
)
@Copyright(year="2009", holder="Natusoft AB", rights="All rights reserved.")
@License(
    type="Apache",
    version="2.0",
    description="Apache Software License",
    source=Source.OPEN,
    text={
        "Licensed under the Apache License, Version 2.0 (the 'License');",
        "you may not use this file except in compliance with the License.",
        "You may obtain a copy of the License at",
        "",
        "  http://www.apache.org/licenses/LICENSE-2.0",
        "",
        "Unless required by applicable law or agreed to in writing, software",
        "distributed under the License is distributed on an 'AS IS' BASIS,",
        "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.",
        "See the License for the specific language governing permissions and",
        "limitations under the License."
    }
)
@Authors({
    @Author(
        name="Tommy Svensson",
        email="tommy@natusoft.se",
        changes={
            @Change(when="2009-12-18", description="Created")
        }
    )
})
public class OMBugException extends OptionsException {

    /**
     * Creates a new OMBugException instance.
     * 
     * @param message The exception message.
     */
    public OMBugException(String message) {
        super("[OptionsManager BUG! Please report this!] " + message);
    }

    /**
     * Creates a new OMBugException instance.
     *
     * @param message The exception message.
     * @param cause The original cause of this exception.
     */
    public OMBugException(String message, Throwable cause) {
        super("[OptionsManager BUG! Please report this!]" + message, cause);
    }
}
